package com.chw.chw.settings.mapper;

import com.chw.chw.settings.domain.DicType;

import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int updateByPrimaryKey(DicType record);

    /**
     * ********************
     * 查询所有的数据字典类型
     * @return
     */
    List<DicType> selectAllDicTypes();

    /**
     * 根据code查询数据字典类型
     * @param code
     * @return
     */
    DicType selectDicTypeByCode(String code);

    /**
     * 保存创建的数据字典类型
     * @param dicType
     * @return
     */
    int insertDicType(DicType dicType);

    /**
     * 根据codes删除数据字典类型
     * @param codes
     * @return
     */
    int deleteDicTypeByCodes(String[] codes);

    /**
     * 保存修改的数据字典类型
     * @param dicType
     * @return
     */
    int updateDicType(DicType dicType);

}