package com.chw.chw.settings.mapper;

import com.chw.chw.settings.domain.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Apr 17 15:39:32 CST 2021
     */
    int updateByPrimaryKey(DicValue record);


    List<DicValue> selectDicValueByTypeCode(String typeCode);

    void deleteDicValueByTypeCodes(String[] codes);

    List<DicValue> selectAllDicValues();

    int insertDicValue(DicValue dicValue);

    int deleteDicValueByIds(String[] ids);

    DicValue selectDicValueById(String id);

    int updateDicValue(DicValue dicValue);
}